global:
  scrape_interval: 30s
  scrape_timeout: 25s

remote_write:
  - url: https://prometheus-prod-43-prod-ap-south-1.grafana.net/api/prom/push
    basic_auth:
      username: 3501192
      password: glc_eyJvIjoiMTg3OTQ5MiIsIm4iOiJzdGFjay0xNzg4NDg0LWFsbG95LWxvY2FsLXNjcmFwcGVyIiwiayI6ImU3UE85YjZuNjEydnZYZ0hXNVg2NWo1UiIsIm0iOnsiciI6InByb2QtYXAtc291dGgtMSJ9fQ==

scrape_configs:
  - job_name: 'nifty-volatility-pipeline'
    metrics_path: '/metrics'
    scheme: 'https'
    static_configs:
      - targets: ["crypto-pipeline-api.onrender.com:443"]